# Generated by Django 4.2.1 on 2023-05-28 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="blog_id",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
            ),
        ),
    ]
