# Generated by Django 4.2.1 on 2023-05-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0001_initial"),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
                (
                    "tag_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tag.tag"
                    ),
                ),
            ],
        ),
    ]
